### ISSUE TITLE
unity3d-dissolve-shader's problem

### ISSUE THREAD

**Issue by puttimeth** [kwnetzwelt/unity3d-dissolve-shader#1]
I have a little problem with your shader.
When I use it with my own object that created from Blender, it won't work like it should do.
Instead of having noise on edge, it's smooth.
[[picture]](https://imgur.com/a/3T2Ep)

**Comment by kwnetzwelt** [comment]
The stretch depends on the UV Map on your mesh data. So you need to make
sure it is not stretched too much.

Regards

puttimeth <notifications@github.com> schrieb am Sa., 14. Okt. 2017, 05:59:

**Comment by puttimeth** [comment]
Thanks for responding!

2017-10-14 12:55 GMT+07:00 Kai Wegner <notifications@github.com>:
